### ISSUE TITLE
1.20.1 verification has failed

### ISSUE THREAD

**Issue by jcurlier** [uhop/node-re2#187] opened 2023-08-16 00:43 UTC
When building the docker image for my backend service on node `18.17.0-alpine` I am getting the following error for `re2` version `1.20.1`:

```
Step 5/8 : RUN npm install --quiet --production
 ---> Running in 82a02ebf4251
npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm ERR! code 1
npm ERR! path /home/app/node_modules/re2
npm ERR! command failed
npm ERR! command sh -c install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild
npm ERR! Trying https://github.com/uhop/node-re2/releases/download/1.20.1/linux-musl-x64-108.br ...
npm ERR! Writing to build/Release/re2.node ...
npm ERR! The verification has failed: building from sources ...
npm ERR! Building locally ...
npm ERR!
npm ERR! > re2@1.20.1 rebuild
npm ERR! > node-gyp rebuild
npm ERR!
npm ERR!
npm ERR! > re2@1.20.1 rebuild
npm ERR! > node-gyp rebuild
npm ERR! gyp ERR! find Python
```

The `re2` dependency is from the package `url-regex-safe` version: `3.0.0` which is from `metascaper`: `5.35.2`

Forcing npm to use re2 version `1.19.1` works. It seems the issue is with the release `1.20.1`

**Comment by leandroaguiar-lr** [comment] 2023-08-16 15:54
Probably a duplicate of https://github.com/uhop/node-re2/issues/180.

**Comment by jcurlier** [comment] 2023-08-16 16:04
Yes looks like it - will monitor that issue - thanks

**Comment by uhop** [comment] 2023-08-23 19:27
>npm ERR! gyp ERR! find Python

Your system does not have Python installed so it cannot build locally.

**Closed by uhop** 2023-08-23 19:27 UTC
Labels: bug
